### ISSUE TITLE
Telegram social icon intermittently changes colors on hover

### ISSUE THREAD

**Issue by SnowdenWintermute** [studentenherz/myrustblog#1]
The other social icons in the footer change to green on hover, but when hovering the Telegram icon it is sometimes yellow and sometimes green.

**Comment by studentenherz** [comment]
Hi, @SnowdenWintermute, thanks for your feedback!

Could you tell me about the system you are using (Web Browser + version at least) so I can try and reproduce the issue?

**Comment by studentenherz** [comment]
Oh, I see, you are probably talking about the RSS icon, not Telegram. I see the issue. I'm hanging the color of the `a` tags to green but the RSS to yellow, and instead of changing its `a` tag's style I'm changing the icon inside it.

**Comment by studentenherz** [comment]
Thanks a lot for your contribution!
